### ISSUE TITLE
Cannot configure package-deps to install package dependancies.

### ISSUE THREAD

**Issue by mrpotatoes** [steelbrain/package-deps#100]
I'm having issues, unfortunately, using your package. I think I've followed your instructions but I'm missing something that is keeping me from greatness.

After putting this code in my package I've published it to Atom packages (`apm publish major/minor`) so that I can see it in the install section of the settings tab in Atom. From there I can install or uninstall the new package. When I install it'll pulldown the package and install the NPM deps (your package) but then it stops there. It doesn't pull down any other package.

Here are the links to the full project (basically empty because I'm trying to get this part to work)

| what  | where |
|---|---|
| `version 2.2.0` | https://github.com/mrpotatoes/re-re-re-react/releases/tag/v2.2.0 |
| `package.json` | https://github.com/mrpotatoes/re-re-re-react/blob/master/package.json |
| `activate()` | https://github.com/mrpotatoes/re-re-re-react/blob/master/lib/re-re-re-react.js#L12 |

Snippets of the code so you don' thave to click the links:
Part of the `package.json`
```js
"dependencies": {
   "atom-package-deps": "4.6.0"
 },

 "package-deps": [
    "atom-beautify",
    "atom-ternjs",
    ... and so on 
  ]
```

The main part of my "`main`" method.
```js
export default {
  // ...
  activate(state) {
    // replace the example argument 'linter-ruby' with the name of this Atom package
    require('atom-package-deps').install('re-re-re-react')
      .then(function() {
      console.log('All dependencies installed, good to go')
    })
  }
  // ...
}
```

**Comment by steelbrain** [comment]
Hi @mrpotatoes 

I see your package has a `activationCommands` key in your `package.json`. Your package will only activate, and therefore install dependencies when that activation command is invoked. If you want your package to install it's dependencies before the activation command is invoked, you could try removing it and listening on the command within the package itself.

Let me know if you have any further questions

**Comment by mrpotatoes** [comment]
That was exactly the problem. Thank you very much!
