### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/package-deps#12]
Make sure we don't break stuff as we progress.

**Comment by steelbrain** [comment]
I'll be discontinuing this when package sets arrive in the core. Until then no change is planned. So yeah it just works™

**Comment by joefitzgerald** [comment]
@steelbrain this line of reasoning is not sound. You are introducing a dependency that has the ability to impact a large part of the atom ecosystem (transitively) because you're integrating it with linter providers. The scope of packages and users that use them cries out for _some tests_. 

The possibility of a future replacement isn't a good reason to omit them if you're shipping this now to tens of thousands of users. Similarly, the fact that it is hard to write tests or that you would need to learn about how to use spies and test http servers to do so is not a good reason to omit them. That it is hard to test is exactly the reason why you need tests - so that it becomes easier to reason about the logic and prevent regression or bad behavior.

**Comment by steelbrain** [comment]
@joefitzgerald: I love tests and I agree 100% with you (also a fan of you). I have discussed it with a friend and now I know how can I write tests for it. but I am kinda busy with personal projects these days and haven't been much active even on linter lately. Now that we have package-deps working, it would be ideal to have tests for it. but due to the shortage of time. I don't think I have enough time to experiment with spies and jasmine APIs.
Considering that it works, and doesn't do much. Just spawns a process and reports the progress. That is something that has been tested by thousands of people. and we haven't had any bug reports yet (only in the beginning), all we get are features and even those have stopped coming now that it's fulfilling it's purpose. We don't plan to ever add anything new to it. We are pretty sure that it doesn't have a bug as it's been tested heavily by the users. so Yeah, I believe that it would be okay if we skip tests for it (not saying that we shouldn't write tests, but considering that I am busy and that users have already tested it). I hope it makes sense.

**Comment by joefitzgerald** [comment]
The reason this line of reasoning doesn't make sense is you use it on almost every project you start. I really want to help you understand how to never get in this situation (write tests first) so we can stop having this conversation.

Learning how to work in this way will help you when it comes time to moving into the professional world of coding (others who are reading, @steelbrain is a student). I'm not saying that test driven development is the only path to success; just that it could help avoid issues like this and commentary from people like me who are dismayed that your good (and very popular) packages have very low test coverage, as this makes contribution much more difficult ("did my change break something? I don't know? No tests to tell me one way or another... I wonder how @steelbrain manually tests? Who knows?").

**Comment by steelbrain** [comment]
> Learning how to work in this way will help you

Yep! Since we started adding tests in linter, I have been adding tests to other projects as well. and thank you for your recommendation of writing tests as we write code (I remember you recommending it on linter as well, it was difficult at first but kept getting simpler), I will keep that in mind when writing more packages.

> your good (and very popular) packages have very low test coverage

Just a side note that linter now has tests for **every** class (except for `Commands` but it has a tracking issue https://github.com/atom-community/linter/issues/842) and every new PR that we accept has tests.

> this makes contribution much more difficult

I agree that it makes contribution difficult, that's why we have tests at linter and I never said that I would **never** add tests for this one, I have said it quite a few times before, saying it again, I love tests and I have nothing against them, they help catch bugs not just for the contributors but myself too.

> I wonder how @steelbrain manually tests

I install a package which has dependencies and confirm that dependencies have been installed. That's what the purpose of this package is, really simple, focused and small.

Anyways, I'm adding tests now. All that you pointed out is valid.

**Comment by steelbrain** [comment]
The specs I've added test the progress bar, installation and activation at the moment. I'll be adding more when I have enough time.
