### ISSUE TITLE
Progress bar does not update

### ISSUE THREAD

**Issue by bolinfest** [steelbrain/package-deps#17]
The async logic in `main.js` is wrong. `Promise.all()` creates one promise that is not fulfilled until all of the packages are installed. Once that happens, `view.markFinished()` is called N times in a row (synchronously). In effect, the user never sees any progress.

Also, if the number of packages to install is large (and the packages themselves are large), then you will likely cause the user's machine to lock up because you are running all of the `apm install` calls in parallel.

**Comment by steelbrain** [comment]
Yep! my bad!
