### ISSUE TITLE
Use package.json To Find Package Name

### ISSUE THREAD

**Issue by joefitzgerald** [steelbrain/package-deps#28]
https://github.com/steelbrain/package-deps/blob/26efdead33d2e447ff10f9c3b45b7e65435525df/lib/main.js#L14-L15 seems flakey and likely to fail in some circumstances. If you simply use __dirname and then walk up the tree until you find package.json, that might be a better approach?

**Comment by steelbrain** [comment]
Nice idea, Thanks!

**Comment by joefitzgerald** [comment]
I suppose you would need to track when you have encountered `node_modules` and use the directory containing that.
