### ISSUE TITLE
Bring option for setting the prompt to off

### ISSUE THREAD

**Issue by aminya** [steelbrain/package-deps#319]
I was using my packages with an option to set the prompt to off. Could you bring this back again? I don't want to rely on the user to accept the every change!

**Comment by steelbrain** [comment]
https://xkcd.com/1172/

**Comment by steelbrain** [comment]
@aminya Do you wanna talk about whether this is a good idea? Things have changed since the last release, there are choices between multiple packages available and users should be allowed to choose which one to go with
