### ISSUE TITLE
Cannot read property 'length' of undefined at lib/index.js:930:26

### ISSUE THREAD

**Issue by lierdakil** [steelbrain/package-deps#321]
See title.

Getting this with the following package deps:
```json
  "package-deps": [
    {
      "name": "atom-ide-ui",
      "minimumVersion": "0.13.0"
    }
  ],
```

**Comment by lierdakil** [comment]
I think this is the issue:
https://github.com/steelbrain/package-deps/blob/c6bf3ee27d03a2e16f1195c126350d3b6a5a3c4c/src/view/atom.ts#L34

**Comment by lierdakil** [comment]
As far as I can tell, that line should read `resolve(ungroupedDependencies)`

**Comment by steelbrain** [comment]
Good catch! And yes you are right, would you like to open a PR?

**Comment by lierdakil** [comment]
I think this would be easier to fix entirely on your end, considering you need to build and publish anyway. I'm not a big fan of one-line PRs.

**Comment by steelbrain** [comment]
I recommended that because I wanted you to get the full attribution for identification and fix

This change is a part of v7.0.2
