### ISSUE TITLE
recommended API slower then necessary

### ISSUE THREAD

**Issue by dirk-thomas** [steelbrain/package-deps#38]
Even with the latest release (3.0.8) the recommended API:

    require('atom-package-deps').install()

is more then twice as slow as passing the package name explicitly:

    require('atom-package-deps').install('linter-NAME')

E.g. with `linter-pyflakes` the time with the recommended call is around 25ms while with the second signature it is around 12ms. So why not recommend the second one?

Beside the performance difference I think 12ms is still significant in the context of dozens of packages using this feature. Users installing a linter through the UI will always have the dependencies installed correctly. Therefore I am not sure if the overhead is justified.

See related discussion on AtomLinter/linter-xmllint#41

**Comment by Arcanemagus** [comment]
Interesting, can you do this to see how much time the guessing of the package name is contributing?
```js
  const start = performance.now()
  if (!name) {
    name = require('atom-package-path').guess()
  }
  console.log("time: " + performance.now() - start)
```

**Comment by steelbrain** [comment]
You might wanna have a look at this, I have stated what eats all the performance there https://github.com/steelbrain/package-deps/issues/35

**Comment by Arcanemagus** [comment]
Ha, just came over here to link to that after seeing it, thanks for debugging that already!

I think the documentation should be updated to recommend specifying the name though if we are taking that hit.

**Comment by dirk-thomas** [comment]
time: 16.610000000000127 ms (+- 2ms)

**Comment by contra** [comment]
I'm having a case where this takes 800ms to happen :(

**Comment by steelbrain** [comment]
@contra That is definitely just too much, do you still get the same numbers on a fresh atom profile? (`mv ~/.atom ~/.atom-bkp`)

**Comment by Arcanemagus** [comment]
@contra are you talking about a package's activation time as reported by Timecop, or the modified code posted above?

**Comment by Arcanemagus** [comment]
@contra as @steelbrain just pointed out https://github.com/AtomLinter/linter-sass-lint/issues/36 to me, what you are seeing there is something entirely different from what we are talking about here (although this _is_ ~30 ms of that.

**Comment by steelbrain** [comment]
Doing further research I found out that **only the first** call to `new Error().stack` costs `~30`ms. That is because atom has deffered all the module requires to when they are first used. If we do another `new Error().stack` after that it only takes upto 2ms which IMO is a fair price.

Closing as only the first module to use atom-package-deps will get that lag and every invocation after that will be fast, so we don't have a performance problem.

**Comment by Arcanemagus** [comment]
Although this may be an acceptable price for performance, I do agree with @dirk-thomas that the _recommended_ method should be to specify the name to cut out the cost in the first place.

**Comment by steelbrain** [comment]
I'd be happy to accept a PR for that :wink:

**Comment by joefitzgerald** [comment]
So as the person who originally asked for magic to identify the package name, I now regret asking for it (although it hasn't impacted me as I've never used that signature). I think the appropriate fix is to just remove the magic.

**Comment by dirk-thomas** [comment]
Please see #41 for an update of the README file recommending to pass the package name explicitly.
