### ISSUE TITLE
Unable to get package info for ...

### ISSUE THREAD

**Issue by jamesdanged** [steelbrain/package-deps#44]
Hi, I've been trying to release a package that relies upon "linter". In my development environment, I've been getting a message "[Package-Deps] Unable to get package info for linter". I'm not sure if this is just what happens when I don't run the installation of my package out of the official repos (I just use `apm link`). It seems when it's trying to run the installation of linter, it tries to get get linter's dependencies, but if it isn't already installed, of course it cannot query them. What might be going on here? I was just using the latest package-deps version.

**Comment by jamesdanged** [comment]
Ah ok, I was supposed to put the name of my own package in the install command, not the names of my dependencies. Sorry about that. Might be good to clarify exactly that in the readme.

**Comment by steelbrain** [comment]
I am glad you figured it out :+1:
