### ISSUE TITLE
packages installed from git repositories are incorrectly treated as not installed

### ISSUE THREAD

**Issue by joelbarker2011** [steelbrain/package-deps#53]
# background

When a `package.json` file contains the following:
```json
"package-deps": [
  "vanilla",
  "githubuser/chocolate"
],
```
the `package-deps` code will install the _vanilla_ package from atom.io and the _chocolate_ package from github.com/githubuser/chocolate. Before installing, it will check whether these packages already exist.

# expected behavior

Both _vanilla_ and _chocolate_ should be installed on first run, and neither should be installed again.

# actual behavior

The _vanilla_ package installs once, and never gets installed again (this is expected).

Unfortunately, the _chocolate_ package gets installed every time Atom is loaded.

# the cause

`package-deps` checks whether a package is installed in [this line from _helpers.js_](https://github.com/steelbrain/package-deps/blob/master/src/helpers.js#L49), using a call to `atom.packages.resolvePackagePath(name)`.

However, `resolvePackagePath(name)` only works for actual package names, so it works for _vanilla_ (and other packages from atom.io), but fails for _githubuser/chocolate_ (because the package name is probably just _chocolate_, but might be something like _atom-chocolate_ if the maintainer decided to use a package name different from the repo name! ;).

# possible solution

The best solution I can think of is to expand the syntax of the `package-deps` JSON key by allowing objects (or perhaps arrays) instead of just strings. The example above would be changed to something like this:
```json
"package-deps": [
  "vanilla",
  { "chocolate": "githubuser/chocolate" }
],
```

(The above object syntax is intended to be similar to the `npm` "dependencies" syntax, but an array or a more structured map would work too.)

If this sounds like a good solution, I can write a pull request (but I'm not familiar with Flow, so it would be straight JS/ES).

**Comment by steelbrain** [comment]
I think an alternative (maybe better?) possible solution would be to do `Path.basename(repoPath)`. Mainly because Atom will do the same and only keep the base name as it's the package name

What do you think?

**Comment by joelbarker2011** [comment]
That won't work for packages like 'steelbrain/package-deps' (where the actual package name is 'atom-package-deps' instead of the basename).

**Comment by steelbrain** [comment]
Ah man, this doesn't get easier now does it 😄 
Alternatively we could do http requests on the repos and get their names from their manifests (and keep a cache of course) and then use that.

Does Atom support installing packages from repos from any other sources than GitHub and BitBucket?

**Comment by joelbarker2011** [comment]
The problem with http requests is that the repos might not exist later (or might be temporarily unavailable); this has come up a few times in Atom issues. Any kind of a cache is liable to get outdated just when you need it.

According to `apm help install`, any kind of "git remote" is allowed (but `apm` does **not** allow the full range of git remotes that `npm help install` supports). I think I've used all of the following:
- user/repo (GitHub)
- bitbucket:user/repo
- https://example.com/user/repo.git
- git+ssh://git@example.com/user/repo.git

(I hope that someday `apm` allows all of the crazy stuff that `npm` allows, like installing a package from a tarball. IMHO, the location/URL of the package should not be tied to the package name at all.)

**Comment by joelbarker2011** [comment]
Since we can't reliably deduce the package name from the package location/URL, it seems to be that the only option is to pass the name in to "package-deps".

Oh, wait, does Atom store the package location/URL somewhere? (I can't find it if it does.)

**Comment by steelbrain** [comment]
Alternatively, we could do it the other way around. We could iterate through manifests of all packages in `~/.atom/packages` and try to match them with the given string.

Now thinking about it, do we really want to support auto-installing packages that have not been published to the APM repository? Because this feature will fall out of the line if we stay focused and only support APM. But then again, if doing a small change here allows a lot of flexibility to consumers, we should definitely consider it. and yet again, if we allow that, what if two different packages from two different sources have the same names? It'll break everything

I personally think that only supporting the packages published to APM is the way to go. What do you think?

**Comment by joelbarker2011** [comment]
> Now thinking about it, do we really want to support auto-installing packages that have not been published to the APM repository?

Yes, because I have to support this in my current project. =D (If necessary, I will have to fork `package-deps` to do this.)

I'll take another look tomorrow. It doesn't seem to me that it should be too difficult or complicate the code too much...

**Comment by joelbarker2011** [comment]
> what if two different packages from two different sources have the same names? It'll break everything

Good point. It looks to me like Atom does not support multiple packages with the same name (`atom.packages.getAvailablePackageNames()` seems to assume that packages will have unique names, for example), so I suppose we shouldn't worry about that scenario.

**Comment by steelbrain** [comment]
Great, so we just have to iterate all loaded packages and check if any of them contain the same repository url as specified by the installee. Sounds good?

**Comment by joelbarker2011** [comment]
Well, I'm afraid it might not be that easy.

**Comment by steelbrain** [comment]
You'll find manifests of all loaded packages in `atom.packages.loadedPackages`, a for-in and check for repo url should be good enough

**Comment by joelbarker2011** [comment]
Resolved by #54 and #55.

**Comment by joelbarker2011** [comment]
Please create a tag `v4.1.1` to point to the latest `HEAD`. Thanks!

**Comment by steelbrain** [comment]
@joelbarker2011 Yeah thanks, I'll be pushing an update where the notifications show correct name instead of repo url in messages before publishing (also we have to `npm publish` before creating tags for it to work)

**Comment by joelbarker2011** [comment]
Awesome, thanks.
