### ISSUE TITLE
Inferring the package name fails on Electron 1.2.x

### ISSUE THREAD

**Issue by maxbrunsfeld** [steelbrain/package-deps#57]
We're in the process of upgrading Atom's version of Electron (https://github.com/atom/atom/pull/12300).

We noticed when using the new Electron, packages that use `package-deps` are throwing exceptions like this:

![screen shot 2016-08-24 at 2 21 23 pm](https://cloud.githubusercontent.com/assets/326587/17948546/1b5ffeb0-6a06-11e6-8ebe-3a9dbf4b89f6.png)

It looks like this module tries to infer the package name from a stack trace, and stack traces for generator functions have changed in the new version of Electron.

**Comment by steelbrain** [comment]
Thanks, investigating

**Comment by joefitzgerald** [comment]
This appears to function correctly if using `atom-package-deps` `v4.2.0`. Any idea what version of the package was in use when that exception was thrown @maxbrunsfeld ?

**Comment by maxbrunsfeld** [comment]
I was seeing this using `v4.2.0`, via `linter-rust` version `0.5.4`.

**Comment by joefitzgerald** [comment]
This is due to the calling package not supplying the package name to install. Still think we should remove the magic: https://github.com/steelbrain/package-deps/issues/38#issuecomment-182096838

**Comment by steelbrain** [comment]
As @joefitzgerald mentioned, It's probably best for all packages to remove the usage of magic and specify the name. But we still have to fix this bug so the upgrade cost between the versions can be reduced and packages can transition at will instead of being stuck at a previous buggy version.
