### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by ricardofbarros** [steelbrain/package-deps#7]
When it's installing the dependencies it doesn't return a promise.

**Comment by steelbrain** [comment]
Some repro code will be appreciated.

**Comment by steelbrain** [comment]
[this line](https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L32) clearly returns a resolved promise if all deps are already installed

**Comment by ricardofbarros** [comment]
```
  require('atom-package-deps')
    .install('linter-js-standard')
    .then(function () {
...
```

**Comment by ricardofbarros** [comment]
Yeah but I think you are missing a `return` in here https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L37

**Comment by steelbrain** [comment]
Ouch. Sorry. Fixing.

**Comment by steelbrain** [comment]
The fix was in https://github.com/steelbrain/package-deps/commit/e77adaa23dd5c6c1ceb8a8698721fc96e81cc306

**Comment by ricardofbarros** [comment]
Unrelated to this issue do you know if there is a way to activate the `linter` package without the need to reload/restart atom?

**Comment by ricardofbarros** [comment]
Nice :+1:

**Comment by steelbrain** [comment]
@ricardofbarros It already activates it after it's installed. No restart required.

**Comment by steelbrain** [comment]
See https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L48
