### ISSUE TITLE
maximum required version

### ISSUE THREAD

**Issue by TeroFrondelius** [steelbrain/package-deps#92]
README says:
> If you need to install specific version of a package, you can add the minimum required version to the package name (semver doesn't work!), separated by ::
> ```
> {
>   "name": "linter-ruby",
>   ...
>   "package-deps": ["linter:2.0.0"]
> }
> ```

Is it possible to have an upper limit of version or one fixed version. Could you do something similar like this:
```
apm install linter-julia@0.5.5
```
I'm trying to find a solution to https://github.com/TeroFrondelius/linter-julia/issues/38 and one short term solution would be reverting to linter version 1.11.21.

**Comment by steelbrain** [comment]
Hi @TeroFrondelius 

The README might need some correction, because it installs the EXACT version given in. So if you specify `0.5.5`, it already does do `apm install linter-julia@0.5.5`

**Comment by TeroFrondelius** [comment]
@steelbrain thanks again.

**Comment by Arcanemagus** [comment]
Note that it will only install a version if the package isn't currently installed!

**Comment by TeroFrondelius** [comment]
@Arcanemagus thanks for the info. I was suspecting something like this.
